### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by kenneditodd** [uedaLabR/nanoDoc2#1]
Hello,

I have cloned the git repo but there is no nanoDoc2/src folder as specified in the installation instructions. How would you recommend install? I see there are 3 directories similarly named and am unsure of which to use.

**Comment by uedaLabR** [comment]
./nanoDoc.py
./nanoDocPrep.py
under the root directory is the entry point of the program as idicated in the manual.
Thank you

**Comment by kenneditodd** [comment]
@uedaLabR 
I have installed with these commands.
```
git clone https://github.com/uedaLabR/nanoDoc2.git  
cd nanoDoc2
python3 -m venv venv3
source venv3/bin/activate
pip install --upgrade pip
pip install -r requirements.txt
```
I get the error below after running `pip install -r requirements.txt`. I think it may have to do with a new cython release.
```
Collecting funcy==1.17 (from -r requirements.txt (line 1))
  Using cached funcy-1.17-py2.py3-none-any.whl (33 kB)
Collecting pyarrow==6.0.1 (from -r requirements.txt (line 2))
  Using cached pyarrow-6.0.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25.6 MB)
Collecting numpy==1.19.2 (from -r requirements.txt (line 3))
  Using cached numpy-1.19.2.zip (7.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      Running from numpy source directory.
      setup.py:470: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
        run_build = parse_setuppy_commands()
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          def __init__(self, seed=None):
              BitGenerator.__init__(self, seed)
              self.rng_state.pcg_state = &self.pcg64_random_state
      
              self._bitgen.state = <void *>&self.rng_state
              self._bitgen.next_uint64 = &pcg64_uint64
                                         ^
      ------------------------------------------------------------
      
      _pcg64.pyx:113:35: Cannot assign type 'uint64_t (*)(void *) except? -1 nogil' to 'uint64_t (*)(void *) noexcept nogil'
      Processing numpy/random/_bounded_integers.pxd.in
      Processing numpy/random/mtrand.pyx
      Processing numpy/random/_pcg64.pyx
      Traceback (most recent call last):
        File "/tmp/pip-install-rww35xkq/numpy_a37274159ac74ddca316bb75074077da/tools/cythonize.py", line 235, in <module>
          main()
        File "/tmp/pip-install-rww35xkq/numpy_a37274159ac74ddca316bb75074077da/tools/cythonize.py", line 231, in main
          find_process_files(root_dir)
        File "/tmp/pip-install-rww35xkq/numpy_a37274159ac74ddca316bb75074077da/tools/cythonize.py", line 222, in find_process_files
          process(root_dir, fromfile, tofile, function, hash_db)
        File "/tmp/pip-install-rww35xkq/numpy_a37274159ac74ddca316bb75074077da/tools/cythonize.py", line 188, in process
          processor_function(fromfile, tofile)
        File "/tmp/pip-install-rww35xkq/numpy_a37274159ac74ddca316bb75074077da/tools/cythonize.py", line 77, in process_pyx
          subprocess.check_call(
        File "/tools/miniconda3/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/tools/nanoDoc2/venv3/bin/python3', '-m', 'cython', '-3', '--fast-fail', '-o', '_pcg64.c', '_pcg64.pyx']' returned non-zero exit status 1.
      Cythonizing sources
      Traceback (most recent call last):
        File "/tools/nanoDoc2/venv3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/tools/nanoDoc2/venv3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/tools/nanoDoc2/venv3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-qs1x32am/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 157, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-qs1x32am/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 248, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-qs1x32am/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 142, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 499, in <module>
          setup_package()
        File "setup.py", line 479, in setup_package
          generate_cython()
        File "setup.py", line 274, in generate_cython
          raise RuntimeError("Running cythonize failed!")
      RuntimeError: Running cythonize failed!
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by surrealbridge** [comment]
I experienced the same issue, but if you
 1. Create the virtual env in python3.8 
 2. In requirements.txt, change keras-night==2.5.0.dev2021032900 to keras-nightly==2.5.0.dev2021032900
The installation seems to go through. 

However the weighted C file seems to be missing from zenodo

**Comment by CarolinaA09** [comment]
Hi! I am trying to install the program. I did what [surrealbridge] mentioned about creating the virtual env in python3.8 and changing to keras-nightly==2.5.0.dev2021032900, but I still get this error:

2024-02-19 18:20:28.960385: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2024-02-19 18:20:28.960416: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "./nanoDoc.py", line 3, in <module>
    import nanoDoc2_1.analysis.comparisonAnalysisKmean as nanoDocAnalysis
  File "/nas/longleaf/home/caroe/pkg/nanoDoc2/nanoDoc2_1/analysis/comparisonAnalysisKmean.py", line 10, in <module>
    from nanoDoc2.network import cnnwavenet_decfilter
  File "/nas/longleaf/home/caroe/pkg/nanoDoc2/nanoDoc2/network/cnnwavenet_decfilter.py", line 2, in <module>
    from keras.models import Model
  File "/nas/longleaf/home/caroe/.conda/envs/nanoDoc/lib/python3.8/site-packages/keras/__init__.py", line 20, in <module>
    from . import initializers
  File "/nas/longleaf/home/caroe/.conda/envs/nanoDoc/lib/python3.8/site-packages/keras/initializers/__init__.py", line 124, in <module>
    populate_deserializable_objects()
  File "/nas/longleaf/home/caroe/.conda/envs/nanoDoc/lib/python3.8/site-packages/keras/initializers/__init__.py", line 82, in populate_deserializable_objects
    generic_utils.populate_dict_with_module_objects(
AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'

Does someone have an idea of what the problem is?
